---
title: "rf2"
output: html_document
editor_options: 
  chunk_output_type: inline
---

dataminingProject<- getwd()
dataminingProject
  setwd(dataminingProject)
 
#kutuphaneler
library(ISLR)

library(tidyverse)

library(funModeling)

library(caret)

library(pROC)

library(class)

library(e1071)

library(kernlab) 

library(ROCR) 

library(neuralnet)

library(GGally)

library(nnet)

library(rpart)

library(cli)

library(tree)

library(rpart.plot)

library(randomForest)

library(gbm)

library(xgboost)

library(DiagrammeR)

library(mlbench)

library(dplyr)

library(ggplot2)



#veri dosyasi okuma
dataSet <- read.csv("C:/Users/Admin/Documents/dataminingProject/data.csv",header = TRUE, sep=";")



#veri inceleme
view(dataSet)
colnames(dataSet)
rownames(dataSet) 
str(dataSet)
summary(dataSet)
library(dplyr)
distinct(dataSet, Marital.status)
distinct(dataSet, Previous.qualification)
any(is.na(dataSet))

# frekans degerleri
table(dataSet$Target)
table(dataSet$GDP)
table(dataSet$Marital.status)
table(dataSet$Curricular.units.2nd.sem..approved.)
table(dataSet$Tuition.fees.up.to.date)

#histogram 

barplot(table(dataSet$Target), main = "Histogram of Academic Success" , xlab = " Success" , ylab = "frekans" , col ="yellow")

hist(dataSet$GDP, col="red", main= "Histogram of GDP ", xlab= "GDP", ylab= "frekans")

hist(dataSet$ Marital.status , col="blue", main= "Histogram of Marital.status ", xlab= " Marital.status ", ylab= "frekans")

hist(dataSet$Curricular.units.2nd.sem..approved. , col="blue", main= "Histogram of Curricular Units 2nd sem Approved ", xlab= " Marital.status ", ylab= "frekans")

hist(dataSet$Tuition.fees.up.to.date , col="blue", main= "Histogram of Tuition.fees.up.to.date ", xlab= " Marital.status ", ylab= "frekans")

#pasta grafigi
pie(table(dataSet$Target), main="Academic Success Distributions", col = c("red" , "yellow" , "blue"))


#Marital Status değişkenini faktör olarak tanımlama
dataSet$Marital.status <- factor(dataSet$Marital.status, levels = c(1, 2, 3, 4, 5, 6),
                              labels = c("Single", "Married", "Widower", "Divorced", "Facto Union", "Legally Separated"))
                              
                              
                              
#Application.mode değişkenini faktör olarak tanımlama
dataSet$Application.mode <- factor(dataSet$Application.mode,
                                levels = c(1, 2, 5, 7, 10, 15, 16, 17, 18, 26, 27, 39, 42, 43, 44, 51, 53, 57),
                                labels = c("1st phase - general contingent",
                                           "Ordinance No. 612/93",
                                           "1st phase - special contingent (Azores Island)",
                                           "Holders of other higher courses",
                                           "Ordinance No. 854-B/99",
                                           "International student (bachelor)",
                                           "1st phase - special contingent (Madeira Island)",
                                           "2nd phase - general contingent",
                                           "3rd phase - general contingent",
                                           "Ordinance No. 533-A/99, item b2) (Different Plan)",
                                           "Ordinance No. 533-A/99, item b3 (Other Institution)",
                                           "Over 23 years old",
                                           "Transfer",
                                           "Change of course",
                                           "Technological specialization diploma holders",
                                           "Change of institution/course",
                                           "Short cycle diploma holders",
                                           "Change of institution/course (International)"))
                            

# Course sütununu faktör olarak tanımlama
dataSet$Course <- factor(dataSet$Course,
                      levels = c(33, 171, 8014, 9003, 9070, 9085, 9119, 9130, 9147, 9238, 9254, 9500, 9556, 9670, 9773, 9853, 9991),
                      labels = c("Biofuel Production Technologies", 
                                  "Animation and Multimedia Design", 
                                  "Social Service (evening attendance)", 
                                  "Agronomy", 
                                  "Communication Design", 
                                  "Veterinary Nursing", 
                                  "Informatics Engineering", 
                                  "Equinculture", 
                                  "Management",
                                  "Social Service", 
                                  "Tourism", 
                                  "Nursing", 
                                  "Oral Hygiene",
                                  "Advertising and Marketing Management", 
                                  "Journalism and Communication", "Basic Education", "Management (evening attendance)"))
                      
                      
                      

#Daytime/evening attendance sütununu faktör olarak tanımlama
dataSet$Daytime.evening.attendance. <- factor(dataSet$Daytime.evening.attendance., levels = c(1, 0), labels = c("daytime", "evening"))





#Previous qualification sütununu sıralı bir faktör olarak tanımlama
dataSet$Previous.qualification <- factor(dataSet$Previous.qualification,
                              levels = c(1, 2, 3, 4, 5, 6, 9, 10, 12, 14, 15, 19, 38, 39, 40, 42, 43),
                              labels = c("Secondary education", "Higher education - bachelor's degree", "Higher education - degree",
                                         "Higher education - master's", "Higher education - doctorate", "Frequency of higher education",
                                         "12th year of schooling - not completed", "11th year of schooling - not completed",
                                         "Other - 11th year of schooling", "10th year of schooling", "10th year of schooling - not completed",
                                         "Basic education 3rd cycle (9th/10th/11th year) or equiv.", "Basic education 2nd cycle (6th/7th/8th year) or equiv.",
                                         "Technological specialization course", "Higher education - degree (1st cycle)", "Professional higher technical course",
                                         "Higher education - master (2nd cycle)"))
                          
#Nationality sütununu faktör olarak tanımlama
dataSet$Nacionality  <- factor(dataSet$Nacionality  ,
                           levels = c(1, 2, 6, 11, 13, 14, 17, 21, 22, 24, 25, 26, 32, 41, 62, 100, 101, 103, 105, 108, 109),
                           labels = c("Portuguese", "German", "Spanish", "Italian", "Dutch", "English", "Lithuanian", "Angolan", "Cape Verdean", "Guinean",
                                      "Mozambican", "Santomean", "Turkish", "Brazilian", "Romanian", "Moldova (Republic of)", "Mexican", "Ukrainian",
                                      "Russian", "Cuban", "Colombian"))
                                      
                                      
                                      
# Mother's qualification sütununu sıralı bir faktör olarak tanımlama
dataSet$Mother.s.qualification  <- factor(dataSet$Mother.s.qualification ,
                                     levels = c(1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 14, 18, 19, 22, 26, 27, 29, 30, 34, 35, 36, 37, 38, 39,40, 41, 42, 43, 44),
                                     labels = c("Secondary Education - 12th Year of Schooling or Eq.", 
                                                "Higher Education - Bachelor's Degree", 
                                                "Higher Education - Degree",
                                                "Higher Education - Master's", 
                                                "Higher Education - Doctorate", 
                                                "Frequency of Higher Education", 
                                                "12th Year of Schooling - Not Completed",
                                                "11th Year of Schooling - Not Completed", 
                                                "7th Year (Old)", "Other - 11th Year of Schooling", 
                                                "10th Year of Schooling", "General Commerce Course",
                                                "Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.", 
                                                "Technical-Professional Course", "7th Year of Schooling", 
                                                "2nd Cycle of the General High School Course",
                                                "9th Year of Schooling - Not Completed", 
                                                "8th Year of Schooling", "Unknown", 
                                                "Can't Read or Write", "Can Read Without  Having a 4th Year of Schooling",   
                                                "Basic Education 1st Cycle (4th/5th Year) or Equiv.", "Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.",                                                        "Technological Specialization Course",
                                                "Higher Education - Degree (1st Cycle)", 
                                                "Specialized Higher Studies Course",
                                                "Professional Higher Technical Course",                                                                                                                                "Higher Education - Master (2nd Cycle)",
                                                "Higher Education - Doctorate (3rd Cycle)"))
                                                
                                                
                                                
# Father's qualification sütununu sıralı bir faktör olarak tanımlama
dataSet$Father.s.qualification <- factor(dataSet$Father.s.qualification,
                                        levels = c(1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14, 18, 19, 20, 22, 25, 26, 27, 29, 30, 31, 33, 34, 35, 36, 37, 38,
                                                   39, 40, 41, 42, 43, 44),
                                        labels = c("Secondary Education - 12th Year of Schooling or Eq.",
                                                    "Higher Education - Bachelor's Degree", "Higher Education -  Degree",
                                                   "Higher Education - Master's", 
                                                   "Higher Education - Doctorate", 
                                                   "Frequency of Higher Education", 
                                                   "12th Year of  Schooling - Not Completed",
                                                   "11th Year of Schooling - Not Completed", 
                                                   "7th Year (Old)", "Other - 11th Year of Schooling", 
                                                   "2nd Year Complementary High School Course",
                                                   "10th Year of Schooling", 
                                                   "General Commerce Course", 
                                                   "Basic Education 3rd Cycle (9th/10th/11th Year) or Equiv.",  
                                                   "Complementary High School Course",
                                                   "Technical-Professional Course", 
                                                   "Complementary High School Course - Not Concluded", 
                                                   "7th Year of Schooling", "2nd  Cycle of the General High School Course",
                                                   "9th Year of Schooling - Not Completed", 
                                                   "8th Year of Schooling", 
                                                   "General Course of Administration and Commerce", 
                                                   "Supplementary Accounting and Administration",
                                                   "Unknown", "Can't Read or Write", 
                                                   "Can Read Without Having a 4th Year of Schooling", 
                                                   "Basic Education 1st Cycle  (4th/5th Year) or Equiv.",
                                                   "Basic Education 2nd Cycle (6th/7th/8th Year) or Equiv.", 
                                                   "Technological Specialization Course", "Higher Education - Degree (1st Cycle)",
                                                   "Specialized Higher Studies Course", 
                                                   "Professional Higher Technical Course", 
                                                   "Higher Education - Master (2nd Cycle)", 
                                                   "Higher Education - Doctorate (3rd Cycle)"))
                                                   
                                                   
                                                   
# Mother's occupation sütununu faktör olarak tanımlama
dataSet$Mother.s.occupation  <- factor(dataSet$Mother.s.occupation ,
                                  levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 90, 99, 122, 123, 125, 131, 132, 134, 141, 143, 144, 151, 152, 153, 171, 173, 175, 191, 192, 193, 194),
                                  labels = c("Student", "Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers",
                                             "Specialists in Intellectual and Scientific Activities", "Intermediate Level Technicians and Professions", "Administrative Staff",
                                             "Personal Services, Security and Safety Workers and Sellers", "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
                                             "Skilled Workers in Industry, Construction and Craftsmen", "Installation and Machine Operators and Assembly Workers", "Unskilled Workers",
                                             "Armed Forces Professions", "Other Situation", "(blank)", "Health professionals", "Teachers", "Specialists in Information and Communication Technologies (ICT)",
                                             "Intermediate Level Science and Engineering Technicians and Professions", "Technicians and Professionals, of Intermediate Level of Health",
                                             "Intermediate Level Technicians from Legal, Social, Sports, Cultural and Similar Services", "Office Workers, Secretaries in General and Data Processing Operators",
                                             "Data, Accounting, Statistical, Financial Services and Registry-related Operators", "Other Administrative Support Staff",
                                             "Personal Service Workers", "Sellers", "Personal Care Workers and the Like", "Skilled Construction Workers and the Like, Except Electricians",
                                             "Skilled Workers in Printing, Precision Instrument Manufacturing, Jewelers, Artisans and the Like",
                                             "Workers in Food Processing, Woodworking, Clothing and Other Industries and Crafts", "Cleaning Workers",
                                             "Unskilled Workers in Agriculture, Animal Production, Fisheries and Forestry",
                                             "Unskilled Workers in Extractive Industry, Construction, Manufacturing and Transport", "Meal Preparation Assistants"))




# Father's occupation sütununu faktör olarak tanımlama
dataSet$Father.s.occupation  <- factor(dataSet$Father.s.occupation ,
                                  levels = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 90, 99, 101, 102, 103, 112, 114, 121, 122, 123, 124, 131, 132, 134, 135, 141, 143, 144, 151, 152, 153, 154, 161, 163, 171, 172, 174, 175, 181, 182, 183, 192, 193, 194, 195),
                                  labels = c("Student",
                                              "Representatives of the Legislative Power and Executive Bodies, Directors, Directors and Executive Managers",
                                             "Specialists in Intellectual and Scientific Activities", 
                                             "Intermediate Level Technicians and Professions", 
                                             "Administrative Staff",
                                             "Personal Services, Security and Safety Workers and Sellers", 
                                             "Farmers and Skilled Workers in Agriculture, Fisheries and Forestry",
                                             "Skilled Workers in Industry, Construction and Craftsmen", 
                                             "Installation and Machine Operators and Assembly Workers", 
                                             "Unskilled Workers",
                                             "Armed Forces Professions", 
                                             "Other Situation", "(blank)", 
                                             "Armed Forces Officers", 
                                             "Armed Forces Sergeants", 
                                             "Other Armed Forces Personnel",
                                             "Directors of Administrative and Commercial Services", 
                                             "Hotel, Catering, Trade and Other Services Directors",
                                             "Specialists in the Physical Sciences, Mathematics, Engineering and Related Techniques", 
                                             "Health Professionals", 
                                             "Teachers",
                                             "Specialists in Finance, Accounting, Administrative Organization, Public and Commercial Relations",
                                             "Intermediate Level Science and Engineering Technicians and Professions",
                                             "Technicians and Professionals, of Intermediate Level of Health",
                                             "Intermediate Level Technicians from Legal, Social, Sports, Cultural and Similar Services",
                                             "Information and Communication Technology Technicians", 
                                             "Office Workers, Secretaries in General and Data Processing Operators",
                                             "Data, Accounting, Statistical, Financial Services and Registry-Related Operators", 
                                             "Other Administrative Support Staff",
                                             "Personal Service Workers", "Sellers", 
                                             "Personal Care Workers and the Like", 
                                             "Protection and Security Services Personnel",
                                             "Market-Oriented Farmers and Skilled Agricultural and Animal Production Workers",
                                             "Farmers, Livestock Keepers, Fishermen, Hunters and Gatherers, Subsistence",
                                             "Skilled Construction Workers and the Like, Except Electricians",
                                             "Skilled Workers in Metallurgy, Metalworking and Similar", 
                                             "Skilled Workers in Electricity and Electronics",
                                             "Workers in Food Processing, Woodworking, Clothing and Other Industries and Crafts",
                                             "Fixed Plant and Machine Operators", 
                                             "Assembly Workers", 
                                             "Vehicle Drivers and Mobile Equipment Operators",
                                             "Unskilled Workers in Agriculture, Animal Production, Fisheries and Forestry",
                                             "Unskilled Workers in Extractive Industry, Construction, Manufacturing and Transport",
                                             "Meal Preparation Assistants", 
                                             "Street Vendors (Except Food) and Street Service Providers"))
                                             
                                             
                                             
# Displaced sütununu faktör olarak tanımlama
dataSet$Displaced <- factor(dataSet$Displaced, levels = c(0, 1), labels = c("No", "Yes"))



# Educational special needs sütununu faktör olarak tanımlama
dataSet$Educational.special.needs  <- factor(dataSet$Educational.special.needs , levels = c(0, 1), labels = c("No", "Yes"))


#Debtor sütununu faktör olarak tanımlama
dataSet$Debtor <- factor(dataSet$Debtor, levels = c(0, 1), labels = c("No", "Yes"))


# Tuition fees up to date sütununu faktör olarak tanımlama
dataSet$Tuition.fees.up.to.date<- factor(dataSet$Tuition.fees.up.to.date, levels = c(0, 1), labels = c("No", "Yes"))

# Gender sütununu faktör olarak tanımlama
dataSet$Gender <- factor(dataSet$Gender, levels = c(0, 1), labels = c("Female", "Male"))



# Scholarship holder sütununu faktör olarak tanımlama
dataSet$Scholarship.holder <- factor(dataSet$Scholarship.holder, levels = c(0, 1), labels = c("No", "Yes"))


# International sütununu faktör olarak tanımlama
dataSet$International <- factor(dataSet$International, levels = c(0, 1), labels = c("No", "Yes"))


# Target sütununu faktör olarak tanımlama
dataSet$Target <- factor(dataSet$Target, levels = c("Dropout", "Enrolled", "Graduate"))


str(dataSet)







#hedef degiskeni factore donusturme
#dataSet$Target <- as.factor(dataSet$Target)


set.seed(123)
train_indeks <- createDataPartition(dataSet$Target,
                                    p = .8, 
                                    list = FALSE,
                                    times = 1)

train <- dataSet[train_indeks,]
test <- dataSet[-train_indeks,]

train_x <- train %>% dplyr::select(-Target)
train_y <- train$Target

test_x <- test %>% dplyr::select(-Target)
test_y <- test$Target

training <- data.frame(train_x, Target = train_y)


#model
rf_fit <- randomForest(train_x,train_y, importance = TRUE)

importance(rf_fit)

varImpPlot(rf_fit)

predict(rf_fit, test_x)

rf_fit


confusionMatrix(predict(rf_fit, train_x), train_y, positive = "Dropout")
confusionMatrix(predict(rf_fit, test_x), test_y, positive = "Dropout")

#grid search

control <- trainControl(method='cv', 
                        number=10, 
                        search='grid')

rf_gridsearch <- train(Target ~ ., 
                       data = train,
                       method = 'rf',
                       metric = 'Accuracy',
                       trControl = control)

(rf_gridsearch)
#1-36 arasında en iyi mtry bulma
set.seed(123) 
tuneGrid <- expand.grid(.mtry = c(1: 36))
rf_mtry <- train(Target ~.,
             data = train,
              method = "rf",
              metric = "Accuracy",
              tuneGrid = tuneGrid,
              trControl = control,
              importance = TRUE,
              nodesize = 14,
              ntree = 300)
print(rf_mtry)

rf_mtry$bestTune$mtry
max(rf_mtry$results$Accuracy)
#en iyi mtry 11 

#grid search
set.seed(123) 
tuneGrid <- expand.grid(.mtry = 11)
rf_mtry <- train(Target ~.,
             data = train,
              method = "rf",
              metric = "Accuracy",
              tuneGrid = tuneGrid,
              trControl = control,
              importance = TRUE,
              nodesize = 14,
              ntree = 300)
confusionMatrix(predict(rf_mtry, train_x), train_y, positive = "Dropout")            
confusionMatrix(predict(rf_mtry, test_x), test_y, positive = "Dropout")


rf_fit <- randomForest(train_x, train_y,ntree = 40, mtry = 11, importance = TRUE)

confusionMatrix(predict(rf_fit, train_x), train_y, positive = "Dropout")
confusionMatrix(predict(rf_fit, test_x), test_y, positive = "Dropout")



rf_fit <- randomForest(train_x, train_y,ntree = 100, mtry =11, maxdepth = 4,minsplit = 3, importance = TRUE)

confusionMatrix(predict(rf_fit, train_x), train_y, positive = "Dropout")
confusionMatrix(predict(rf_fit, test_x), test_y, positive = "Dropout")























